-- SECURITY NOTICE: Never commit service role credentials to version control.
-- The SUPABASE_SERVICE_ROLE_KEY must be added to Supabase Vault manually after deployment.
--
-- Run the following in the Supabase SQL editor, replacing <YOUR_SERVICE_ROLE_KEY>
-- with the actual key from Project Settings → API:
--
--   insert into vault.secrets (name, description, secret)
--   values (
--     'SUPABASE_SERVICE_ROLE_KEY',
--     'Internal key for triggering edge functions from Postgres',
--     '<YOUR_SERVICE_ROLE_KEY>'
--   )
--   on conflict (name) do update set secret = excluded.secret;
